spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database:
      url: jdbc:postgresql://localhost:5439/postgres
      username: postgres
      password: postgres